"""Type stubs for pymysql.connections."""

from types import TracebackType
from typing import Any, Optional, Type

from pymysql.cursors import Cursor

class Connection:
    open: bool
    def cursor(self, cursor: Optional[Type[Any]] = ...) -> Cursor: ...
    def close(self) -> None: ...
    def ping(self, reconnect: bool = ...) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> "Connection": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None: ...
