"""Type stubs for pymysql.cursors."""

from types import TracebackType
from typing import Any, Optional, Type

class Cursor:
    def execute(self, query: str, args: object = ...) -> int: ...
    def fetchone(self) -> Any: ...
    def fetchall(self) -> Any: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Cursor": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None: ...

class DictCursor(Cursor): ...
class SSCursor(Cursor): ...
class SSDictCursor(Cursor): ...
