"""Configuration management."""

from __future__ import annotations

import configparser
from pathlib import Path
from typing import Optional

from check_mysql.core.exceptions import ConfigurationError
from check_mysql.core.models import MySQLConfig, SSHConfig

NAGIOS_ETC_DIRS = ("/usr/local/etc/nagios", "/etc/nagios")

SSH_COMMENTED_SECTION = """\
# --- SSH tunnel (optional) --------------------------------------------------
# Uncomment this section to reach MySQL through an SSH bastion: the plugin
# opens the tunnel first, then connects to [mysql] host:port THROUGH it
# (the MySQL host is resolved from the bastion's point of view).
#
#[ssh]
#host = bastion.example.com
#port = 22
#user = nagios
# Authenticate with a private key (recommended) or a password:
#private_key = ~/.ssh/id_ed25519
#password = only-if-no-key
"""

DEFAULT_CONFIG_TEMPLATE = (
    """\
# check_mysql configuration — generated by `check_mysql init`.
# Edit the credentials below, then try: check_mysql uptime

# --- Direct connection ------------------------------------------------------
[mysql]
host = localhost
port = 3306
user = nagios
password = change-me
# Optional default schema:
#database = mydb
# Connection timeout in seconds:
timeout = 10

"""
    + SSH_COMMENTED_SECTION
)


def load_config(config_path: str = "check_mysql.ini") -> configparser.ConfigParser:
    """
    Load configuration from file.

    Raises:
        FileNotFoundError: If no configuration file can be located.
    """
    config = configparser.ConfigParser()

    config_file = _find_config_file(config_path)

    if not config_file or not Path(config_file).exists():
        raise FileNotFoundError(f"Configuration file not found: {config_path}")

    config.read(config_file)
    return config


def _find_config_file(config_path: str) -> Optional[str]:
    """Find the configuration file in the current directory or Nagios etc directories."""
    # If absolute path provided, use it
    if Path(config_path).is_absolute():
        return config_path

    # Try current directory
    current_dir = Path.cwd() / config_path
    if current_dir.exists():
        return str(current_dir)

    # Try well-known Nagios configuration directories
    for base in NAGIOS_ETC_DIRS:
        candidate = Path(base) / config_path
        if candidate.exists():
            return str(candidate)

    # Return original path (will fail later if not found)
    return config_path


def write_config(config_path: str, content: str, force: bool = False) -> Path:
    """
    Write a configuration file to disk (mode 600 — it carries a password).

    Raises:
        ConfigurationError: If the file already exists and force is False.
    """
    path = Path(config_path)
    if path.exists() and not force:
        raise ConfigurationError(f"{path} already exists — use --force to overwrite")
    path.write_text(content, encoding="utf-8")
    path.chmod(0o600)
    return path


def write_default_config(
    config_path: str = "check_mysql.ini", force: bool = False
) -> Path:
    """
    Write the default configuration template to disk (mode 600).

    The template ships a ready-to-edit ``[mysql]`` section and a commented ``[ssh]`` section
    enabling the tunnel once uncommented. Overwrite handling (ConfigurationError without ``force``)
    comes from :func:`write_config`.
    """
    return write_config(config_path, DEFAULT_CONFIG_TEMPLATE, force)


def render_config(mysql: MySQLConfig, ssh: Optional[SSHConfig] = None) -> str:
    """
    Render a configuration file for the given settings.

    The ``[ssh]`` section is written active when tunnel settings are given, and shipped commented
    (ready to enable) otherwise.
    """
    lines: list[str] = [
        "# check_mysql configuration — generated by `check_mysql init`.",
        "",
        "[mysql]",
        f"host = {mysql.host}",
        f"port = {mysql.port}",
        f"user = {mysql.user}",
        f"password = {mysql.password}",
    ]
    if mysql.database:
        lines.append(f"database = {mysql.database}")
    lines += [f"timeout = {mysql.timeout}", ""]

    if ssh is None:
        lines.append(SSH_COMMENTED_SECTION.rstrip("\n"))
    else:
        lines += [
            "# --- SSH tunnel --------------------------------------------------------",
            "[ssh]",
            f"host = {ssh.host}",
            f"port = {ssh.port}",
            f"user = {ssh.user}",
        ]
        if ssh.private_key:
            lines.append(f"private_key = {ssh.private_key}")
        if ssh.password:
            lines.append(f"password = {ssh.password}")
    return "\n".join(lines) + "\n"


def get_mysql_config(
    config: configparser.ConfigParser,
    hostname: Optional[str] = None,
    port: Optional[int] = None,
) -> MySQLConfig:
    """Build the MySQL settings from the ``[mysql]`` section, with CLI overrides."""
    mysql = MySQLConfig()
    if config.has_section("mysql"):
        section = config["mysql"]
        mysql.host = section.get("host", mysql.host)
        mysql.port = section.getint("port", mysql.port)
        mysql.user = section.get("user", mysql.user)
        mysql.password = section.get("password", mysql.password)
        mysql.database = section.get("database", mysql.database)
        mysql.timeout = section.getint("timeout", mysql.timeout)
    if hostname is not None:
        mysql.host = hostname
    if port is not None:
        mysql.port = port
    return mysql


def get_security_allowlist(config: configparser.ConfigParser) -> frozenset[str]:
    """
    Accounts (``user@host``) exempted by the optional ``[security]`` section.

    The ``allow`` option holds comma- or newline-separated entries matching
    the User and Host columns of mysql.user exactly. The option is read raw,
    so ``%`` hosts need no escaping. Returns an empty set when the section or
    the option is absent.
    """
    if not config.has_section("security"):
        return frozenset()
    value = config.get("security", "allow", raw=True, fallback="")
    entries = (entry.strip() for entry in value.replace("\n", ",").split(","))
    return frozenset(entry for entry in entries if entry)


def get_ssh_config(config: configparser.ConfigParser) -> Optional[SSHConfig]:
    """
    Build the SSH tunnel settings from the optional ``[ssh]`` section.

    Returns None when the section is absent (direct connection).

    Raises:
        ConfigurationError: If the section is present but incomplete.
    """
    if not config.has_section("ssh"):
        return None

    section = config["ssh"]
    host = section.get("host", "")
    user = section.get("user", "")
    if not host or not user:
        raise ConfigurationError("[ssh] section requires both host and user")

    password = section.get("password", None)
    private_key = section.get("private_key", None)
    if not password and not private_key:
        raise ConfigurationError("[ssh] section requires a password or a private_key")
    if private_key:
        private_key = str(Path(private_key).expanduser())

    return SSHConfig(
        host=host,
        port=section.getint("port", 22),
        user=user,
        password=password,
        private_key=private_key,
    )
