"""Type stubs for nagiosplugin."""

from typing import Any, Iterable, NoReturn, Sequence, Union

class ServiceState:
    code: int
    text: str
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

Ok: ServiceState
Warn: ServiceState
Critical: ServiceState
Unknown: ServiceState

class Range:
    invert: bool
    start: float
    end: float
    def __new__(cls, spec: Union[str, int, float, "Range", None] = ...) -> "Range": ...
    def match(self, value: Union[int, float]) -> bool: ...
    def __contains__(self, value: Union[int, float]) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def violation(self) -> str: ...

class Metric:
    name: str
    value: Any
    uom: str | None
    min: float | None
    max: float | None
    context: str | None
    contextobj: "Context | None"
    resource: "Resource | None"
    def __new__(
        cls,
        name: str,
        value: Any,
        uom: str | None = ...,
        min: float | None = ...,
        max: float | None = ...,
        context: str | None = ...,
        contextobj: "Context | None" = ...,
        resource: "Resource | None" = ...,
    ) -> "Metric": ...
    def replace(self, **attr: Any) -> "Metric": ...
    @property
    def description(self) -> str: ...
    @property
    def valueunit(self) -> str: ...
    def evaluate(self) -> "Result": ...
    def performance(self) -> "Performance | None": ...

class Result:
    state: ServiceState
    hint: str | None
    metric: Metric | None
    def __new__(
        cls,
        state: ServiceState,
        hint: str | None = ...,
        metric: Metric | None = ...,
    ) -> "Result": ...
    def __str__(self) -> str: ...
    @property
    def resource(self) -> "Resource | None": ...
    @property
    def context(self) -> "Context | None": ...

class Results:
    results: list[Result]
    def __init__(self, *results: Result) -> None: ...
    def add(self, *results: Result) -> "Results": ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: Union[int, str]) -> Result: ...
    def __contains__(self, name: str) -> bool: ...  # type: ignore[override]
    @property
    def most_significant_state(self) -> ServiceState: ...
    @property
    def most_significant(self) -> list[Result]: ...
    @property
    def first_significant(self) -> Result: ...

class Resource:
    @property
    def name(self) -> str: ...
    def probe(self) -> Sequence[Metric] | Iterable[Metric] | Metric | list[Any]: ...

class Context:
    name: str
    fmt_metric: Any
    result_cls: type[Result]
    def __init__(
        self,
        name: str,
        fmt_metric: Any = ...,
        result_cls: type[Result] = ...,
    ) -> None: ...
    def evaluate(self, metric: Metric, resource: Resource) -> Result: ...
    def performance(
        self, metric: Metric, resource: Resource
    ) -> "Performance | None": ...
    def describe(self, metric: Metric) -> str | None: ...

class ScalarContext(Context):
    warning: Range
    critical: Range
    def __init__(
        self,
        name: str,
        warning: Union[str, int, float, Range, None] = ...,
        critical: Union[str, int, float, Range, None] = ...,
        fmt_metric: str = ...,
        result_cls: type[Result] = ...,
    ) -> None: ...
    def evaluate(self, metric: Metric, resource: Resource) -> Result: ...
    def performance(self, metric: Metric, resource: Resource) -> "Performance": ...

class Summary:
    def ok(self, results: Results) -> str: ...
    def problem(self, results: Results) -> str: ...
    def verbose(self, results: Results) -> list[str] | str: ...
    def empty(self) -> str: ...

class Performance:
    def __init__(
        self,
        label: str,
        value: Any,
        uom: str | None = ...,
        warn: Range | None = ...,
        crit: Range | None = ...,
        min: float | None = ...,
        max: float | None = ...,
    ) -> None: ...
    def __str__(self) -> str: ...

class Check:
    resources: list[Resource]
    summary: Summary
    results: Results
    perfdata: list[str]
    name: str
    def __init__(self, *objects: Any, **kwargs: Any) -> None: ...
    def add(self, *objects: Any) -> "Check": ...
    def __call__(self) -> None: ...
    def main(
        self, verbose: int | None = ..., timeout: int | None = ...
    ) -> NoReturn: ...
    @property
    def state(self) -> ServiceState: ...
    @property
    def summary_str(self) -> str: ...
    @property
    def verbose_str(self) -> str | list[str]: ...
    @property
    def exitcode(self) -> int: ...

class CheckError(Exception): ...
class Timeout(Exception): ...

class Runtime:
    def execute(
        self, check: Check, verbose: int | None = ..., timeout: int | None = ...
    ) -> NoReturn: ...

class Cookie: ...
class LogTail: ...
class MultiArg: ...

def guarded(func: Any) -> Any: ...

__version__: str
